### ISSUE TITLE
Refactor error handling 

### ISSUE THREAD

**Issue by tiero** [vulpemventures/custodian-vault#11]
As stated here https://github.com/vulpemventures/custodian-vault/pull/8 we should find a more scalable way to throw, manage and identify specific errors and meanings.

For reference:

https://blog.golang.org/errors-are-values
https://github.com/pkg/errors
https://github.com/0x4139/bitcoin-p2sh/tree/master/tests

**Comment by altafan** [comment]
can this be closed?
